# Generated by Django 6.0.2 on 2026-02-20 01:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sdp_id', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('icon_key', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sdp_id', models.CharField(db_index=True, max_length=50, unique=True)),
                ('display_id', models.CharField(blank=True, max_length=20)),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(blank=True, max_length=50)),
                ('author', models.CharField(blank=True, max_length=200)),
                ('updated_sdp', models.CharField(blank=True, help_text="Display value from SDP (e.g. 'Mar 29, 2023')", max_length=100)),
                ('hits', models.IntegerField(default=0)),
                ('keywords', models.CharField(blank=True, max_length=500)),
                ('is_public', models.BooleanField(default=False)),
                ('synced_at', models.DateTimeField(auto_now=True, help_text='Last time this record was synced from SDP')),
                ('topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solutions', to='api.topic')),
            ],
            options={
                'ordering': ['-sdp_id'],
            },
        ),
    ]
